#Config details for server related information
SERVER-DETAILS:
  SERVER-ADDRESS: localhost
  SERVER-PORT: 5000
  PORT-ENABLED: true
#Config details for HTTPS/TLS/SSL information
HTTPS-DETAILS:
  HTTPS-ENABLED: false
  CERTIFICATE-FILE: None
  KEY_FILE: None
#Config details for database information
DATABASE-DETAILS:
  USERNAME: test
  PASSWORD: test01
  DATABASE-TYPE: sqlite
  DATABASE-NAME: test.db
  DATABASE-URI: C:\Users\voidl\Desktop\Swinburne\SEPB\Application\eos-application\server\modules\database\