#A list of configuration options for the server across three sections:
#  - Server Details: details for creating the server endpoint to connect and send requests.
#  - HTTPS Details: details to setup TLS/SSL on the server.
#  - Database details: details specifying the database connection (either mysql or sqlite).
SERVER-DETAILS:
  SERVER-ADDRESS: localhost #the address to setup the server on (FQDN or IP)
  SERVER-PORT: 5000 #the port to setup the server on
  PORT-ENABLED: true #is to be set to true as the server requires a port
HTTPS-DETAILS:
  HTTPS-ENABLED: false #whether the server is to have TLS/SSL and require HTTPS
  CERTIFICATE-FILE: None #the location/path of the certificate file for TLS 
  KEY_FILE: None #the location/path of the key file for TLS
DATABASE-DETAILS:
  USERNAME: test #the database account username
  PASSWORD: test01 #the database account password
  DATABASE-TYPE: sqlite #the database type (sqlite or mysql)
  DATABASE-NAME: test.db #the database name
  DATABASE-URI:  /home/devmain/uni-work/app-resources/eos-app/server/modules/database/ #the database uri (path or address) with a \ or / on the end
 
