SERVER-DETAILS:
  SERVER-ADDRESS: localhost
  SERVER-PORT: 5000
  HTTPS-ENABLED: false
HTTPS-DETAILS:
  CERTIFICATE-FILE: None
  KEY_FILE: None
DATABASE-DETAILS:
  USERNAME: test
  PASSWORD: test01
  DATABASE: test.db
  DATABASE-URI: sqlite:////home/devmain/uni-work/app-resources/eos-app/server/modules/database/